### ISSUE TITLE
is it possible to change progress speed

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [2hamed/ProgressCircula#2]
سلام امکان این هست که سرعت پروگرس کم یا زیاد بشه؟
الان یک باگی هست که پروگرس حالت 
indeterminate
هست اولش با یک کندی و سرعت پایینی پروگرس میچرخه ، ولی بعد از حدود 5 ثانیه سرعت درست میشه

**Comment by 2hamed** [comment]
added the `speed` factor. Check docs for v0.2.
